apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ivy-cache-volume-claim
  labels:
    app: iototal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: ivy-cache-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ivy-cache-volume
  labels:
    app: iototal
spec:
  hostPath:
    path: /data/ivy-cache
    type: DirectoryOrCreate
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  
  