apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
  labels:
    app: iototal
spec:
  ports:
  - name: minio
    port: 9000
    targetPort: 9000
  - name: minio-console
    port: 9090
    targetPort: 9090
  selector:
    app: iototal
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: default
  labels:
    app: iototal
spec:
  ports:
  - name: minio
    port: 9000
    targetPort: 9000
  clusterIP: None
  selector:
    app: iototal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: default
  labels:
    app: iototal
spec:
  serviceName: "minio-headless"
  replicas: 1
  selector:
    matchLabels:
      app: iototal
  template:
    metadata:
      labels:
        app: iototal
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9090
          name: console
        volumeMounts:
        - mountPath: /data
          name: data
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio
              key: accessKey
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretKey
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]  # Changed from ReadWriteMany for GKE compatibility
      storageClassName: "standard-rwo"  # Explicitly specify GKE storage class
      resources:
        requests:
          storage: 10Gi
