apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: default
  labels:
    app: iototal
type: Opaque
data:
  accessKey: bWluaW9hZG1pbg==
  secretKey: bWluaW9hZG1pbg==
  endpoint: aHR0cDovL21pbmlvLWhlYWRsZXNzOjkwMDA=